name: Clean Except 'new' Folder

on:
  workflow_dispatch: # لتشغيله يدويًا

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove all files and folders except 'new'
      run: |
        shopt -s extglob
        # يمسح كل شيء ما عدا 'new'
        rm -rf !(new)
